name: Deploy to Production

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd ${{ secrets.SERVER_APP_PATH }}
          git pull
          docker compose -f docker-compose.prod.yml up -d --build
          docker system prune -f
